### ISSUE TITLE
Deprecate legacy API in favor of traversable API (files)

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#80]
The ``files()`` API completely supersedes the earlier APIs through a simpler and more intuitive interface. In order to achieve "one and preferably only one" interface for the same behavior, it's desirable to remove the legacy API.

In GitLab by @jaraco on Feb 22, 2020, 09:33

Following from !76 and [this comment](https://gitlab.com/python-devs/importlib_resources/issues/58#note_289528564), I'd like to explore what the implementation would look like with only the traversable API. In that comment, I wrote:

> I've started stripping out [the legacy] functionality in the [feature/drop-legacy-api branch](https://gitlab.com/python-devs/importlib_resources/-/tree/feature/drop-legacy-api). Progress was good, but I got stumped on `Traversable.open()` for zip files, which doesn't support text-decoding. This leads me to believe that's a feature [zipp should support](https://github.com/jaraco/zipp/issues/44). This also suggests the `Traversable` API should include `.open()`.

# Plan

- [x] Update implementation of legacy API functions to rely on `files`. Tests still pass. (#221)
- [x] Develop and document transition guidance. (#236)
- [x] Mark legacy API with DeprecationWarnings. (#236)
- [x] Create/adapt test suite such that `files` API is covered entirely by tests not using legacy API. (#239)
- [x] Port to CPython for ~~3.10~~3.11.
- [x] Freeze legacy implementation.
- [ ] Remove legacy implementation.
- [ ] Port to CPython for ~~3.11~~3.13+.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Feb 29, 2020, 20:37

In #81, we're adding `.open()` to the traversable API.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 1, 2020, 11:15

mentioned in commit a8a471c5514c63627f4c709e453937f13787a557

**Comment by FFY00** [comment]
What is required for this? I assume writing some quick snippets on how to migrate from the old API to the new one, and while doing that make sure all features from the old API have an equivalent in the new one.

This could also potentially be done at the same time as #108, what do you think?

**Comment by jaraco** [comment]
Thanks for asking.

> I assume writing some quick snippets on how to migrate from the old API to the new one, and while doing that make sure all features from the old API have an equivalent in the new one.

Good plan. Note that most of the test coverage is against the legacy API. I was thinking something along these lines:

- Update implementation of legacy API functions to rely on `files`. Tests still pass.
- Develop and document transition guidance.
- Mark legacy API with DeprecationWarnings.
- Create/adapt test suite such that `files` API is covered entirely by tests not using legacy API.
- Port to CPython for 3.10.
- Freeze legacy implementation.
- Remove legacy implementation.
- Port to CPython for 3.11.

Some of these steps are optional if superseded by subsequent steps (such as freezing legacy implementation).

I've already updated the documentation for [porting from pkg_resources](https://github.com/python/importlib_resources/blob/master/docs/migration.rst) to use the `files`/`traversable` API, so that may also provide some hints as to how to migrate from the importlib_resources legacy API.

I notice that the docs are not synced at all with CPython, so there will be a separate effort (but coordinated) of deprecating the API in `importlib.resources`. That process will have a longer timeline, as it will need to be deprecated in one Python version (no earlier than 3.10) and removed in one or two versions later (probably one, as users have a fallback in `importlib_resources`).

> This could also potentially be done at the same time as #108,

It may prove easier if #108 is done first, though I wouldn't have one block on the other. I've got some thoughts I'll add on that ticket.

**Comment by FFY00** [comment]
I have opened #221 which reimplements the legacy API using `files()`. Overall it seems to be able to replace most of it, falling short in just one feature, `importlib.resources.path`. Traversables are designed as purely abstract, with no ties to the file system, which makes it impossible to replace `path`. I have opened bpo-44200, which proposes a fix for that.

**Comment by jaraco** [comment]
> makes it impossible to replace `path`

What about `as_file(files(...).joinpath(...))`? `as_file` takes a Traversable file and creates a path for it on the file system. It's meant to be the replacement for `path`.

**Comment by FFY00** [comment]
`as_file` will always create a temporary file, `path` documents that it will only do that if the resource isn't on the file system. `as_path` replaces it in essence, but not as `path` is documented. I probably shouldn't have used "impossible" to describe it, but `as_file` does go against what `path` documents, and has an undesirable behavior IMO.

I think there are valid use-cases for wanting this `path` behavior. One example would be big resources, let's say I have a 10gb dataset, I don't want to copy that to a temporary file.

Something to consider: On most Linux distributions, `/tmp` is a `tmpfs`, which lives on the RAM. If I create a 10gb file there, I will be putting 10gb on the RAM. You can see how this could go wrong... even for smaller files...

**Comment by jaraco** [comment]
`as_file` [uses singledispatch](https://github.com/python/importlib_resources/blob/1886e2b9d699c55afc1b75dc19e7026ad27e453a/importlib_resources/_common.py#L109) to avoid creating temporary objects when the traversable is a pathlib.Path. So in the most common case, temporary files should not be created.

**Comment by FFY00** [comment]
Right, but that is simply mitigating the issue on the most common case, not actually fixing the issue in the interface.

One example where that will not work is `CompatibilityFiles`, if we choose to go with that.

I would really prefer to fix the interface, but it's your call.

**Comment by jaraco** [comment]
I'd like to see what it means to fix the interface, but for the purposes of this effort, I suspect `as_file` is sufficient to satisfy the needs of `path`. Am I mistaken?

**Comment by FFY00** [comment]
I would say yes, but it won't necessarily stay true to its docstring. What you get is pretty much the same, the documented details on how you get it will not stay true in some cases.

**Comment by coldfix** [comment]
Hi,

I know you've discussed the deprecation in other threads with the SC and probably considered it through already. Anyway, I wanted to add my perspective as a (insignificant) library and application developer.

My desire is to make my software as compatible as possible. God knows many people do not install the latest version of their linux distribution every year. I want to support at least all the non-EOL python versions and not introduce backward breakage unless there is a good reason. Heck, there are still many people python 3.6, e.g. ubuntu 18.04 users, some of which may even stay around until after its EOL in 2023.

With the deprecation of the *legacy* API, I will now receive issues about deprecation warnings and first have to research what do to about it. First thing, it's not optimal that I'm being sent around to look for the fix: The warning links to an URL and that page says to look in the code. I may now be able to use that code for upgrading to the new API, but it doesn't tell me what [options](https://github.com/python/steering-council/issues/68#issuecomment-947377186) I have for supporting both versions:

1. implement the change without backward compatibility path in my code. Absolute no go because I want to continue supporting python 3.7
2. leave the code as is. Not good because users will (understandably) get intimidated by the warning, and some may even stop using my software because they feel unsafe or feel that it's not well-maintained anymore
3. add code to silence the warning. Not a good long term solution, since it's unclear **when** you will be removing the old API, so I'll have to remember to check every so often for updates on this.
4. pin a specific (old or new) `importlib_resources` version. Not a good option because another specific (new or old) version of `importlib_resources` may be distributed with the operating system. Doing this may force users to install my package in a virtualenv - which may be fine for technical folks, but can considerably complicate the installation process otherwise
5. integrate a specific version of the library into my codebase. Obviously not great when I'm just using this for a one-time use of one of the functions
6. research for a more stable alternative library (I'm on it, and really, I have to research something more stable than standard library? :()
7. add forward-compatible try-except code like this:

```python
try:
    from importlib.resources import files

    def open_binary(package, resource):
        return (files(package) / normalize_path(resource)).open('rb')
except ImportError:
    from importlib.resources import open_binary
```

The 1 line import has to be replaced by 7 lines of compatibility code for just one of those functions (times number of downstream applications), while it is 3 lines for each of these function in your code base. In fact, the deprecation increases the maintenance load even in your package and adds about 20 lines to your code base (not counting tests).

Also, did you spot the bug in the code above? Yes. It uses a `normalize_path` function that is (I think?) not part of your public API, so I'll have to copy that one as well, or myself evaluate whether I can safely remove it. Effectively, not even the "upgrade" path (option 1 above) is documented as of yet. This is not made easier by the fact that the *legacy" API doesn't seem to be documented anymore and your online documentation doesn't provide builds of older releases (or I couldn't find any at least).

And this is not even the first time I got hit with a backward incompatibility in importlib_resources (that I wasn't even warned about at the time).

Honestly, if I were to do this in a smaller library, people would just stop using it, so I'd have be very careful and only do it if absolutely necessary and provide better migration paths. For a library that gets also integrated into the standard library I think it should be the bare minimum to wait until all non-EOL python versions have access to the new features and provide a more well-documented migration path. Changes like this quickly cost tens of thousands of hours of downstream developer time. And I don't really understand the maintenance cost introduced by keeping around a few one-liner wrapper functions in your code base, but I doubt it would cost you more than the energy you invest into deprecating it, even if there were no "resistence". All that for introducing a new API of which many people will use only the subset that was easier to with the old API. (I know that I currently only use two or three of the legacy functions in my projects)

Anyway I appreciate your efforts in making this library and none of this is to attack you personally, but rather to offer perspective.

**Comment by jaraco** [comment]
It's time! Let's remove the legacy implementation.

**Comment by jaraco** [comment]
There once was a branch (`feature/drop-legacy-api`), but it's now stale, so I've pushed it to `refs/archive/drop-legacy-api-naive` and deleted it.
